services:
  app:
    image: ituacm-website:latest # veya build: .
    # build:
    #   context: .
    expose:
      - "80" # container İÇ portu; senin imajın 80'de 200 veriyor demiştin
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik-public

      # Service (app iç portu)
      traefik.http.services.website.loadbalancer.server.port: "80"

      # HTTP router (HTTPS'i sonra ekleriz)
      traefik.http.routers.website-http.rule: "Host(`ituacm.com`) || Host(`www.ituacm.com`)"
      traefik.http.routers.website-http.entrypoints: http
      traefik.http.routers.website-http.middlewares: https-redirect # HTTP'yi HTTPS'e it

      # HTTPS router
      traefik.http.routers.website-https.rule: "Host(`ituacm.com`) || Host(`www.ituacm.com`)"
      traefik.http.routers.website-https.entrypoints: https
      traefik.http.routers.website-https.tls: "true"
      traefik.http.routers.website-https.tls.certresolver: le

    networks:
      - traefik-public
    restart: always

networks:
  traefik-public:
    external: true
