services:
  app:
    image: ituacm-website:latest
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public

      # SERVICE (container iç portun kaç ise: 80/3000/5173)
      - traefik.http.services.website-app.loadbalancer.server.port=80

      # HTTP -> HTTPS redirect
      - traefik.http.routers.website-app-http.rule=Host(`ituacm.com`) || Host(`www.ituacm.com`)
      - traefik.http.routers.website-app-http.entrypoints=http
      - traefik.http.routers.website-app-http.middlewares=https-redirect

      # HTTPS router (asıl trafik)
      - traefik.http.routers.website-app-https.rule=Host(`ituacm.com`) || Host(`www.ituacm.com`)
      - traefik.http.routers.website-app-https.entrypoints=https
      - traefik.http.routers.website-app-https.tls=true
      - traefik.http.routers.website-app-https.tls.certresolver=le

    networks:
      - traefik-public
      - default
    build:
      context: .
    platform: linux/amd64 # Patch for M1 Mac

networks:
  traefik-public:
    external: true
